[pkgs]
nodejs = "18.14.0"  # Replace "18" with your preferred Node.js version

[phases.setup]
run = "cd server && npm install"
pkgs = ["nodejs"]

[variables]
NODE_VERSION = "18.14.0"

[phases.start]
run = "cd server && node app.js"