import { ActionType } from "./types";

export const ACTION_CAPTURE_FINGERPRINT: ActionType = 'ACTION_CAPTURE_FINGERPRINT';
export const ACTION_INITIALIZE_DATABASES: ActionType = 'ACTION_INITIALIZE_DATABASES';
export const ACTION_ADD_DATABASE: ActionType = 'ACTION_ADD_DATABASE';
export const ACTION_REMOVE_DATABASE: ActionType = 'ACTION_REMOVE_DATABASE';
export const ACTION_SWITCH_ACTIVE_DATABASE: ActionType = 'ACTION_SWITCH_ACTIVE_DATABASE';